# Generated by Django 4.2 on 2024-09-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGoldenCafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
